services:
  stats-db:
    image: postgres:16.1
    container_name: statistics-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6542:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d stats"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: main-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "6541:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm -d ewm"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-db:
    image: postgres:16.1
    container_name: user-db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "6543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d user" ]
      interval: 5s
      timeout: 5s
      retries: 10

  event-db:
    image: postgres:16.1
    container_name: event-db
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
    ports:
      - "6545:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U event -d event" ]
      interval: 5s
      timeout: 5s
      retries: 10