aggregator:
  kafka:
    consumer:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": "stats.aggregator"
        "group.id": "aggregator.group.id"
        "key.deserializer": org.apache.kafka.common.serialization.LongDeserializer
        "value.deserializer": ru.practicum.kafka.deserializer.UserActionAvroDeserializer
        "max.poll.records": 100
        "fetch.max.bytes": 3072000
        "max.partition.fetch.bytes": 3072000

    producer:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": "stats.aggregator"
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.practicum.kafka.serializer.GeneralAvroSerializer
        "linger.ms": 0

    topics:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1

    consume-attempt-timeout-millis: 1000

logging:
  level:
    org:
      slf4j: DEBUG
    ru.practicum: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.client.discovery: DEBUG