spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: admin_categories_route
          uri: lb://main-service
          predicates:
            - Path=/admin/categories/**

        - id: public_categories_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**


        - id: admin_compilation_route
          uri: lb://main-service
          predicates:
            - Path=/admin/compilations/**

        - id: public_compilation_route
          uri: lb://main-service
          predicates:
            - Path=/compilations/**


        - id: user_comment_event_route
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/comments/**

        - id: user_comment_all_user_comments_route
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/comments/**

        - id: public_comment_event_route
          uri: lb://main-service
          predicates:
            - Path=/events/{eventId}/comments/**

        - id: admin_comment_event_route
          uri: lb://main-service
          predicates:
            - Path=/admin/comments/**


        - id: user_event_route
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/events/**

        - id: admin_event_route
          uri: lb://main-service
          predicates:
            - Path=/admin/events/**

        - id: public_event_route
          uri: lb://main-service
          predicates:
            - Path=/events/**


        - id: user_request_route
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/requests/**


        - id: admin_user_route_delete
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.slf4j: DEBUG
    ru.practicum: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.client.discovery: DEBUG